# Generated by Django 5.1.7 on 2025-03-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='outline',
            field=models.CharField(default='', max_length=255),
        ),
    ]
