# Generated by Django 5.1.7 on 2025-03-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_tags_post_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImages',
        ),
    ]
